### PR TITLE
Fix example for avakar_packet.h

### PR DESCRIPTION
**Pull request by JarekParal**

### CODE REVIEW

**Comment by yaqwsx** [comment]
Where's the fix?

**Comment by JarekParal** [comment]
Here: https://github.com/yaqwsx/Atoms/pull/3/commits/d3178176f3c4fd07a507af4a38eaaae08f44accc#diff-ef872c270b3d5acc46d9dbaf3d1ce4bdR58

**Comment by yaqwsx** [comment]
It is not a fix. There's a note you could do that, however why would you do that, when the program ends?

**Comment by JarekParal** [comment]
The fix is in the comment: `in.reset()` -> `in.clear()`

The comment is not enough for me.

**Comment by yaqwsx** [comment]
Ok, my mistake. Please change only the comment, do not add code. It makes impression it is necessary to call every time.

**Pull request merged**
